# 
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#
# Текстовые метки и сообщения, используемые FISSION
#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±

#
# Настройки
#

#
# Сообщения
#

{100}{}{Отключение Широкого экрана отключит}
{101}{}{расширенные настройки.}
{102}{}{Вы уверены, что продолжить?}
{103}{}{Изменения графики вступят в силу}
{104}{}{после перезапуска.}
{105}{}{Режим Игровой зоны 'Ориг.' отключит}

#
# Изменённые настройки
#

{110}{}{Влиять на скорость вне боя}

#
# Доп. Заголовки
#

{124}{}{ЭКРАН}
{125}{}{РАСТЯЖЕНИЕ}
{126}{}{КАЧЕСТВО}
{127}{}{ИГРОВАЯ ЗОНА}
{128}{}{} #Leave blank
{129}{}{} #Leave blank

#
# Доп. Метки
#

{225}{}{Выкл}
{226}{}{Полный экран}        
{227}{}{Выкл}        
{228}{}{Широкий экран} 
{229}{}{Выкл}           
{230}{}{Растянуть} 
{231}{}{Выкл}
{232}{}{Соотношение сторон}
{233}{}{Выкл}         
{234}{}{Высокое качество}        
{235}{}{Выкл}
{236}{}{Квадратные пиксели}
{237}{}{Ориг}      
{238}{}{Умолч}        
{239}{}{Больш}  
{240}{}{Огр}  

#
# Fission About
#

{300}{}{F.I.S.S.I.O.N.}
{301}{}{Гибкая изометрическая система симуляции}
{302}{}{для интерактивной открытой ядерной ролевой игры}

#
# Sort Context Menu
#

# Player actions (400-404)
{400}{}{Вы упорядочиваете рюкзак по категориям.}
{401}{}{Вы перемещаете оружие наверх.}
{402}{}{Вы перемещаете боеприпасы наверх.}
{403}{}{Вы перемещаете препараты наверх.}
{404}{}{Вы перемещаете разные предметы наверх.}
{405}{}{Вы сортируете инвентарь по весу.}
{406}{}{Вы сортируете инвентарь по стоимости.}
{407}{}{Вы сортируете инвентарь в обратном порядке.}

# Other inventory actions (410-414) - with %s for object name
{410}{}{Инвентарь %s упорядочен по категориям.}
{411}{}{Оружие %s перемещено наверх.}
{412}{}{Боеприпасы %s перемещены наверх.}
{413}{}{Препараты %s перемещены наверх.}
{414}{}{Разные предметы %s перемещены наверх.}
{415}{}{Инвентарь %s отсортирован по весу.}
{416}{}{Инвентарь %s отсортирован по стоимости.}
{417}{}{Инвентарь %s отсортирован в обратном порядке.}

# No items messages (450-453)
{450}{}{Нет оружия для сортировки.}
{451}{}{Нет боеприпасов для сортировки.}
{452}{}{Нет препаратов для сортировки}
{453}{}{Нет разных предметов для сортировки.}

# Empty inventory messages
{460}{}{Ваш инвентарь уже «оптимизирован».}
{461}{}{Здесь серьёзная нехватка возможностей для сортировки.}

#
# Меню загрузки модов
#

# Названия
{500}{}{ЗАГРУЖЕНЫ МОДЫ}
{501}{}{ГОТОВО}
{502}{}{ОТМЕНА}

{503}{}{кем}

# Всплывающее окно перезапуска
{510}{}{Изменения в порядке модов вступят в силу}
{511}{}{при перезапуске.}

