#include "sfall_config.h"

#include "db.h"
#include "platform_compat.h"
#include "scan_unimplemented.h"
#include "settings.h"
#include <stdio.h>
#include <string.h>

namespace fallout {

#define DIR_SEPARATOR '/'

bool gModConfigInitialized = false;
Config gModConfig;

bool modConfigInit(int argc, char** argv)
{
    if (gModConfigInitialized) {
        return false;
    }

    if (!configInit(&gModConfig)) {
        return false;
    }

    // Initialize defaults – grouped by category

    // Mod Settings
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_START_YEAR, MOD_CONFIG_DEFAULT_START_YEAR);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_START_MONTH, MOD_CONFIG_DEFAULT_START_MONTH);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_START_DAY, MOD_CONFIG_DEFAULT_START_DAY);
    configSetString(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_STARTING_MAP_KEY, MOD_CONFIG_DEFAULT_STARTING_MAP);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_MOVIE_TIMER_ARTIMER1, MOD_CONFIG_DEFAULT_MOVIE_TIMER_ARTIMER1);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_MOVIE_TIMER_ARTIMER2, MOD_CONFIG_DEFAULT_MOVIE_TIMER_ARTIMER2);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_MOVIE_TIMER_ARTIMER3, MOD_CONFIG_DEFAULT_MOVIE_TIMER_ARTIMER3);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_MOVIE_TIMER_ARTIMER4, MOD_CONFIG_DEFAULT_MOVIE_TIMER_ARTIMER4);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_PIPBOY_AVAILABLE_AT_GAMESTART, MOD_CONFIG_DEFAULT_PIPBOY_AVAILABLE_AT_GAMESTART);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_OVERRIDE_CRITICALS_MODE_KEY, MOD_CONFIG_DEFAULT_OVERRIDE_CRITICALS_MODE);
    configSetString(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_OVERRIDE_CRITICALS_FILE_KEY, MOD_CONFIG_DEFAULT_OVERRIDE_CRITICALS_FILE);
    configSetString(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_PREMADE_CHARACTERS_FILE_NAMES_KEY, MOD_CONFIG_DEFAULT_PREMADE_CHARACTERS_FILE_NAMES);
    configSetString(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_PREMADE_CHARACTERS_FACE_FIDS_KEY, MOD_CONFIG_DEFAULT_PREMADE_CHARACTERS_FACE_FIDS);
    configSetString(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_DUDE_NATIVE_LOOK_JUMPSUIT_MALE_KEY, MOD_CONFIG_DEFAULT_DUDE_NATIVE_LOOK_JUMPSUIT_MALE);
    configSetString(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_DUDE_NATIVE_LOOK_JUMPSUIT_FEMALE_KEY, MOD_CONFIG_DEFAULT_DUDE_NATIVE_LOOK_JUMPSUIT_FEMALE);
    configSetString(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_DUDE_NATIVE_LOOK_TRIBAL_MALE_KEY, MOD_CONFIG_DEFAULT_DUDE_NATIVE_LOOK_TRIBAL_MALE);
    configSetString(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_DUDE_NATIVE_LOOK_TRIBAL_FEMALE_KEY, MOD_CONFIG_DEFAULT_DUDE_NATIVE_LOOK_TRIBAL_FEMALE);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_MAIN_MENU_BIG_FONT_COLOR_KEY, MOD_CONFIG_DEFAULT_MAIN_MENU_BIG_FONT_COLOR);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_MAIN_MENU_CREDITS_OFFSET_X_KEY, MOD_CONFIG_DEFAULT_MAIN_MENU_CREDITS_OFFSET_X);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_MAIN_MENU_CREDITS_OFFSET_Y_KEY, MOD_CONFIG_DEFAULT_MAIN_MENU_CREDITS_OFFSET_Y);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_MAIN_MENU_FONT_COLOR_KEY, MOD_CONFIG_DEFAULT_MAIN_MENU_FONT_COLOR);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_MAIN_MENU_OFFSET_X_KEY, MOD_CONFIG_DEFAULT_MAIN_MENU_OFFSET_X);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_MAIN_MENU_OFFSET_Y_KEY, MOD_CONFIG_DEFAULT_MAIN_MENU_OFFSET_Y);
    configSetString(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_VERSION_STRING, MOD_CONFIG_DEFAULT_VERSION_STRING);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_WORLDMAP_TRAIL_MARKERS, MOD_CONFIG_DEFAULT_WORLDMAP_TRAIL_MARKERS);

    // Additional Mod Settings (recently added defaults)
    configSetString(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_KARMA_FRMS_KEY, MOD_CONFIG_DEFAULT_KARMA_FRMS);
    configSetString(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_KARMA_POINTS_KEY, MOD_CONFIG_DEFAULT_KARMA_POINTS);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_DYNAMITE_MIN_DAMAGE_KEY, MOD_CONFIG_DEFAULT_DYNAMITE_MIN_DAMAGE);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_DYNAMITE_MAX_DAMAGE_KEY, MOD_CONFIG_DEFAULT_DYNAMITE_MAX_DAMAGE);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_PLASTIC_EXPLOSIVE_MIN_DAMAGE_KEY, MOD_CONFIG_DEFAULT_PLASTIC_EXPLOSIVE_MIN_DAMAGE);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_PLASTIC_EXPLOSIVE_MAX_DAMAGE_KEY, MOD_CONFIG_DEFAULT_PLASTIC_EXPLOSIVE_MAX_DAMAGE);
    configSetString(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_CITY_REPUTATION_LIST_KEY, MOD_CONFIG_DEFAULT_CITY_REPUTATION_LIST);
    configSetString(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_UNARMED_FILE_KEY, MOD_CONFIG_DEFAULT_UNARMED_FILE);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_DAMAGE_MOD_FORMULA_KEY, MOD_CONFIG_DEFAULT_DAMAGE_MOD_FORMULA);
    configSetBool(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_BONUS_HTH_DAMAGE_FIX_KEY, MOD_CONFIG_DEFAULT_BONUS_HTH_DAMAGE_FIX);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_USE_LOCKPICK_FRM_KEY, MOD_CONFIG_DEFAULT_USE_LOCKPICK_FRM);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_USE_STEAL_FRM_KEY, MOD_CONFIG_DEFAULT_USE_STEAL_FRM);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_USE_TRAPS_FRM_KEY, MOD_CONFIG_DEFAULT_USE_TRAPS_FRM);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_USE_FIRST_AID_FRM_KEY, MOD_CONFIG_DEFAULT_USE_FIRST_AID_FRM);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_USE_DOCTOR_FRM_KEY, MOD_CONFIG_DEFAULT_USE_DOCTOR_FRM);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_USE_SCIENCE_FRM_KEY, MOD_CONFIG_DEFAULT_USE_SCIENCE_FRM);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_USE_REPAIR_FRM_KEY, MOD_CONFIG_DEFAULT_USE_REPAIR_FRM);
    configSetBool(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_SCIENCE_REPAIR_TARGET_TYPE_KEY, MOD_CONFIG_DEFAULT_SCIENCE_REPAIR_TARGET_TYPE);
    configSetBool(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_GAME_DIALOG_FIX_KEY, MOD_CONFIG_DEFAULT_GAME_DIALOG_FIX);
    configSetString(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_TWEAKS_FILE_KEY, MOD_CONFIG_DEFAULT_TWEAKS_FILE);
    configSetBool(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_GAME_DIALOG_GENDER_WORDS_KEY, MOD_CONFIG_DEFAULT_GAME_DIALOG_GENDER_WORDS);
    configSetBool(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_TOWN_MAP_HOTKEYS_FIX_KEY, MOD_CONFIG_DEFAULT_TOWN_MAP_HOTKEYS_FIX);

    // Game Fixes
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_USE_WALK_DISTANCE, MOD_CONFIG_DEFAULT_USE_WALK_DISTANCE);

    // Files and Paths
    configSetString(&gModConfig, MOD_CONFIG_SCRIPTS_KEY, MOD_CONFIG_INI_CONFIG_FOLDER, MOD_CONFIG_DEFAULT_INI_CONFIG_FOLDER);
    configSetString(&gModConfig, MOD_CONFIG_SCRIPTS_KEY, MOD_CONFIG_GLOBAL_SCRIPT_PATHS, MOD_CONFIG_DEFAULT_GLOBAL_SCRIPT_PATHS);
    configSetString(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_PATCH_FILE, MOD_CONFIG_DEFAULT_PATCH_FILE);
    configSetString(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_EXTRA_MESSAGE_LISTS_KEY, MOD_CONFIG_DEFAULT_EXTRA_MESSAGE_LISTS);
    configSetString(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_BOOKS_FILE_KEY, MOD_CONFIG_DEFAULT_BOOKS_FILE);
    configSetString(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_ELEVATORS_FILE_KEY, MOD_CONFIG_DEFAULT_ELEVATORS_FILE);
    configSetString(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_CONSOLE_OUTPUT_FILE_KEY, MOD_CONFIG_DEFAULT_CONSOLE_OUTPUT_FILE);

    // Mods (Burst)
    configSetBool(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_BURST_MOD_ENABLED_KEY, MOD_CONFIG_DEFAULT_BURST_MOD_ENABLED);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_BURST_MOD_CENTER_MULTIPLIER_KEY, MOD_CONFIG_BURST_MOD_DEFAULT_CENTER_MULTIPLIER);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_BURST_MOD_CENTER_DIVISOR_KEY, MOD_CONFIG_BURST_MOD_DEFAULT_CENTER_DIVISOR);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_BURST_MOD_TARGET_MULTIPLIER_KEY, MOD_CONFIG_BURST_MOD_DEFAULT_TARGET_MULTIPLIER);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_BURST_MOD_TARGET_DIVISOR_KEY, MOD_CONFIG_BURST_MOD_DEFAULT_TARGET_DIVISOR);

    // Others (Interface Bar, etc.)
    configSetBool(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_IFACE_BAR_MODE, MOD_CONFIG_DEFAULT_IFACE_BAR_MODE);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_IFACE_BAR_WIDTH, MOD_CONFIG_DEFAULT_IFACE_BAR_WIDTH);
    configSetInt(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_IFACE_BAR_SIDE_ART, MOD_CONFIG_DEFAULT_IFACE_BAR_SIDE_ART);
    configSetBool(&gModConfig, MOD_CONFIG_SETTINGS_KEY, MOD_CONFIG_IFACE_BAR_SIDES_ORI, MOD_CONFIG_DEFAULT_IFACE_BAR_SIDES_ORI);

    char path[COMPAT_MAX_PATH];
    snprintf(path, sizeof(path), "data%c%s",
        DIR_SEPARATOR, MOD_CONFIG_FILE_NAME);

    auto configChecker = ConfigChecker(gModConfig, MOD_CONFIG_FILE_NAME);

    configRead(&gModConfig, path, true); // true = is Database (dat)

    // Load any mod override files (mod_*.cfg) from the same directory
    char searchPattern[COMPAT_MAX_PATH];
    snprintf(searchPattern, sizeof(searchPattern), "data%c%s",
        DIR_SEPARATOR, "mod_*.cfg");

    char** modFiles = nullptr;
    int modFileCount = fileNameListInit(searchPattern, &modFiles);

    if (modFileCount > 0) {
        // fileNameListInit returns alphabetically sorted list - can't determine priority of 'mods' for now
        for (int i = 0; i < modFileCount; i++) {
            char modPath[COMPAT_MAX_PATH];
            snprintf(modPath, sizeof(modPath), "data%c%s",
                DIR_SEPARATOR, modFiles[i]);

            // Additive reading of config settings from the mod override file
            configRead(&gModConfig, modPath, true);
        }

        fileNameListFree(&modFiles, modFileCount);
    }

    configParseCommandLineArguments(&gModConfig, argc, argv);
    configChecker.check(gModConfig);

    // read mod settigs into main settings
    settingsFromModConfig();

    gModConfigInitialized = true;

    return true;
}

void modConfigExit()
{
    if (gModConfigInitialized) {
        configFree(&gModConfig);
        gModConfigInitialized = false;
    }
}

} // namespace fallout
