#ifndef MOD_CONFIG_H
#define MOD_CONFIG_H

#include "config.h"
#include "platform_compat.h"

namespace fallout {

#define MOD_CONFIG_FILE_NAME "mod.cfg" // set this to mod 'configuration' file, kept in dat - one level down - new name "fission.cfg"?

// Changed category headers for better crouping in .cfg file
#define MOD_CONFIG_SETTINGS_KEY "mod_settings"
#define MOD_CONFIG_SCRIPTS_KEY "mod_scripts"

// ---- mod.cfg settings ----
#define MOD_CONFIG_VERSION_STRING "VersionString"
#define MOD_CONFIG_START_YEAR "StartYear"
#define MOD_CONFIG_START_MONTH "StartMonth"
#define MOD_CONFIG_START_DAY "StartDay"
#define MOD_CONFIG_MOVIE_TIMER_ARTIMER1 "MovieTimer_artimer1"
#define MOD_CONFIG_MOVIE_TIMER_ARTIMER2 "MovieTimer_artimer2"
#define MOD_CONFIG_MOVIE_TIMER_ARTIMER3 "MovieTimer_artimer3"
#define MOD_CONFIG_MOVIE_TIMER_ARTIMER4 "MovieTimer_artimer4"
#define MOD_CONFIG_PIPBOY_AVAILABLE_AT_GAMESTART "PipBoyAvailableAtGameStart"
#define MOD_CONFIG_SCIENCE_REPAIR_TARGET_TYPE_KEY "ScienceOnCritters"
#define MOD_CONFIG_USE_LOCKPICK_FRM_KEY "Lockpick"
#define MOD_CONFIG_USE_STEAL_FRM_KEY "Steal"
#define MOD_CONFIG_USE_TRAPS_FRM_KEY "Traps"
#define MOD_CONFIG_USE_FIRST_AID_FRM_KEY "FirstAid"
#define MOD_CONFIG_USE_DOCTOR_FRM_KEY "Doctor"
#define MOD_CONFIG_USE_SCIENCE_FRM_KEY "Science"
#define MOD_CONFIG_USE_REPAIR_FRM_KEY "Repair"
#define MOD_CONFIG_DYNAMITE_MIN_DAMAGE_KEY "Dynamite_DmgMin"
#define MOD_CONFIG_DYNAMITE_MAX_DAMAGE_KEY "Dynamite_DmgMax"
#define MOD_CONFIG_PLASTIC_EXPLOSIVE_MIN_DAMAGE_KEY "PlasticExplosive_DmgMin"
#define MOD_CONFIG_PLASTIC_EXPLOSIVE_MAX_DAMAGE_KEY "PlasticExplosive_DmgMax"
#define MOD_CONFIG_PREMADE_CHARACTERS_FILE_NAMES_KEY "PremadePaths" // requires parsing/modification
#define MOD_CONFIG_PREMADE_CHARACTERS_FACE_FIDS_KEY "PremadeFIDs" // requires parsing/modification
#define MOD_CONFIG_OVERRIDE_CRITICALS_MODE_KEY "OverrideCriticalTable"
#define MOD_CONFIG_OVERRIDE_CRITICALS_FILE_KEY "OverrideCriticalFile"
#define MOD_CONFIG_DAMAGE_MOD_FORMULA_KEY "DamageFormula"
#define MOD_CONFIG_STARTING_MAP_KEY "StartingMap"
#define MOD_CONFIG_KARMA_FRMS_KEY "KarmaFRMs" // requires parsing/modification
#define MOD_CONFIG_KARMA_POINTS_KEY "KarmaPoints" // requires parsing/modification
#define MOD_CONFIG_MAIN_MENU_BIG_FONT_COLOR_KEY "MainMenuBigFontColour"
#define MOD_CONFIG_MAIN_MENU_CREDITS_OFFSET_X_KEY "MainMenuCreditsOffsetX"
#define MOD_CONFIG_MAIN_MENU_CREDITS_OFFSET_Y_KEY "MainMenuCreditsOffsetY"
#define MOD_CONFIG_MAIN_MENU_FONT_COLOR_KEY "MainMenuFontColour"
#define MOD_CONFIG_MAIN_MENU_OFFSET_X_KEY "MainMenuOffsetX"
#define MOD_CONFIG_MAIN_MENU_OFFSET_Y_KEY "MainMenuOffsetY"
#define MOD_CONFIG_DUDE_NATIVE_LOOK_JUMPSUIT_MALE_KEY "MaleDefaultModel"
#define MOD_CONFIG_DUDE_NATIVE_LOOK_JUMPSUIT_FEMALE_KEY "FemaleDefaultModel"
#define MOD_CONFIG_DUDE_NATIVE_LOOK_TRIBAL_MALE_KEY "MaleStartModel"
#define MOD_CONFIG_DUDE_NATIVE_LOOK_TRIBAL_FEMALE_KEY "FemaleStartModel"
#define MOD_CONFIG_GAME_DIALOG_GENDER_WORDS_KEY "DialogGenderWords"
#define MOD_CONFIG_WORLDMAP_TRAIL_MARKERS "WorldMapTravelMarkers"

// game fixes - hide, but turn off with strictVanilla?
#define MOD_CONFIG_USE_WALK_DISTANCE "UseWalkDistance"
#define MOD_CONFIG_TOWN_MAP_HOTKEYS_FIX_KEY "TownMapHotkeysFix"
#define MOD_CONFIG_GAME_DIALOG_FIX_KEY "DialogueFix"
#define MOD_CONFIG_BONUS_HTH_DAMAGE_FIX_KEY "BonusHtHDamageFix"

// files and paths - add to mod settings
#define MOD_CONFIG_INI_CONFIG_FOLDER "IniConfigFolder"
#define MOD_CONFIG_GLOBAL_SCRIPT_PATHS "GlobalScriptPaths" // requires parsing/modification
#define MOD_CONFIG_PATCH_FILE "PatchFile"
#define MOD_CONFIG_EXTRA_MESSAGE_LISTS_KEY "ExtraGameMsgFileList" // requires parsing/modification
#define MOD_CONFIG_TWEAKS_FILE_KEY "TweaksFile"
#define MOD_CONFIG_CITY_REPUTATION_LIST_KEY "CityRepsList" // requires parsing/modification
#define MOD_CONFIG_UNARMED_FILE_KEY "UnarmedFile"
#define MOD_CONFIG_BOOKS_FILE_KEY "BooksFile"
#define MOD_CONFIG_ELEVATORS_FILE_KEY "ElevatorsFile"
#define MOD_CONFIG_CONSOLE_OUTPUT_FILE_KEY "ConsoleOutputPath"

// mods - add to mod settings?
#define MOD_CONFIG_BURST_MOD_ENABLED_KEY "ComputeSprayMod"
#define MOD_CONFIG_BURST_MOD_CENTER_MULTIPLIER_KEY "ComputeSpray_CenterMult"
#define MOD_CONFIG_BURST_MOD_CENTER_DIVISOR_KEY "ComputeSpray_CenterDiv"
#define MOD_CONFIG_BURST_MOD_TARGET_MULTIPLIER_KEY "ComputeSpray_TargetMult"
#define MOD_CONFIG_BURST_MOD_TARGET_DIVISOR_KEY "ComputeSpray_TargetDiv"

// others - scrap or add to mod settings?
#define MOD_CONFIG_IFACE_BAR_MODE "IFACE_BAR_MODE"
#define MOD_CONFIG_IFACE_BAR_WIDTH "IFACE_BAR_WIDTH"
#define MOD_CONFIG_IFACE_BAR_SIDE_ART "IFACE_BAR_SIDE_ART"
#define MOD_CONFIG_IFACE_BAR_SIDES_ORI "IFACE_BAR_SIDES_ORI"

// ---- mod.cfg settings default values ----
#define MOD_CONFIG_DEFAULT_START_YEAR 2241
#define MOD_CONFIG_DEFAULT_START_MONTH 6
#define MOD_CONFIG_DEFAULT_START_DAY 24
#define MOD_CONFIG_DEFAULT_STARTING_MAP ""
#define MOD_CONFIG_DEFAULT_MOVIE_TIMER_ARTIMER1 90
#define MOD_CONFIG_DEFAULT_MOVIE_TIMER_ARTIMER2 180
#define MOD_CONFIG_DEFAULT_MOVIE_TIMER_ARTIMER3 270
#define MOD_CONFIG_DEFAULT_MOVIE_TIMER_ARTIMER4 360
#define MOD_CONFIG_DEFAULT_PIPBOY_AVAILABLE_AT_GAMESTART 0
#define MOD_CONFIG_DEFAULT_OVERRIDE_CRITICALS_MODE 2
#define MOD_CONFIG_DEFAULT_OVERRIDE_CRITICALS_FILE ""
#define MOD_CONFIG_DEFAULT_PREMADE_CHARACTERS_FILE_NAMES ""
#define MOD_CONFIG_DEFAULT_PREMADE_CHARACTERS_FACE_FIDS ""
#define MOD_CONFIG_DEFAULT_DUDE_NATIVE_LOOK_JUMPSUIT_MALE ""
#define MOD_CONFIG_DEFAULT_DUDE_NATIVE_LOOK_JUMPSUIT_FEMALE ""
#define MOD_CONFIG_DEFAULT_DUDE_NATIVE_LOOK_TRIBAL_MALE ""
#define MOD_CONFIG_DEFAULT_DUDE_NATIVE_LOOK_TRIBAL_FEMALE ""
#define MOD_CONFIG_DEFAULT_MAIN_MENU_BIG_FONT_COLOR 0
#define MOD_CONFIG_DEFAULT_MAIN_MENU_CREDITS_OFFSET_X 0
#define MOD_CONFIG_DEFAULT_MAIN_MENU_CREDITS_OFFSET_Y 0
#define MOD_CONFIG_DEFAULT_MAIN_MENU_FONT_COLOR 0
#define MOD_CONFIG_DEFAULT_MAIN_MENU_OFFSET_X 0
#define MOD_CONFIG_DEFAULT_MAIN_MENU_OFFSET_Y 0
#define MOD_CONFIG_DEFAULT_VERSION_STRING ""
#define MOD_CONFIG_DEFAULT_WORLDMAP_TRAIL_MARKERS 0

// Game fixes
#define MOD_CONFIG_DEFAULT_USE_WALK_DISTANCE 5

// Files and paths
#define MOD_CONFIG_DEFAULT_INI_CONFIG_FOLDER ""
#define MOD_CONFIG_DEFAULT_GLOBAL_SCRIPT_PATHS ""
#define MOD_CONFIG_DEFAULT_PATCH_FILE ""
#define MOD_CONFIG_DEFAULT_EXTRA_MESSAGE_LISTS ""
#define MOD_CONFIG_DEFAULT_BOOKS_FILE ""
#define MOD_CONFIG_DEFAULT_ELEVATORS_FILE ""
#define MOD_CONFIG_DEFAULT_CONSOLE_OUTPUT_FILE ""

// Mods (Burst)
#define MOD_CONFIG_DEFAULT_BURST_MOD_ENABLED 0
#define MOD_CONFIG_BURST_MOD_DEFAULT_CENTER_MULTIPLIER 1
#define MOD_CONFIG_BURST_MOD_DEFAULT_CENTER_DIVISOR 3
#define MOD_CONFIG_BURST_MOD_DEFAULT_TARGET_MULTIPLIER 1
#define MOD_CONFIG_BURST_MOD_DEFAULT_TARGET_DIVISOR 2

#define MOD_CONFIG_DEFAULT_IFACE_BAR_MODE 1
#define MOD_CONFIG_DEFAULT_IFACE_BAR_WIDTH 800
#define MOD_CONFIG_DEFAULT_IFACE_BAR_SIDE_ART 0
#define MOD_CONFIG_DEFAULT_IFACE_BAR_SIDES_ORI 0
#define MOD_CONFIG_DEFAULT_KARMA_FRMS ""
#define MOD_CONFIG_DEFAULT_KARMA_POINTS ""
#define MOD_CONFIG_DEFAULT_DYNAMITE_MIN_DAMAGE 30
#define MOD_CONFIG_DEFAULT_DYNAMITE_MAX_DAMAGE 50
#define MOD_CONFIG_DEFAULT_PLASTIC_EXPLOSIVE_MIN_DAMAGE 40
#define MOD_CONFIG_DEFAULT_PLASTIC_EXPLOSIVE_MAX_DAMAGE 80
#define MOD_CONFIG_DEFAULT_CITY_REPUTATION_LIST ""
#define MOD_CONFIG_DEFAULT_UNARMED_FILE ""
#define MOD_CONFIG_DEFAULT_DAMAGE_MOD_FORMULA 0
#define MOD_CONFIG_DEFAULT_BONUS_HTH_DAMAGE_FIX 1

// Skill FRM overrides
#define MOD_CONFIG_DEFAULT_USE_LOCKPICK_FRM 293
#define MOD_CONFIG_DEFAULT_USE_STEAL_FRM 293
#define MOD_CONFIG_DEFAULT_USE_TRAPS_FRM 293
#define MOD_CONFIG_DEFAULT_USE_FIRST_AID_FRM 293
#define MOD_CONFIG_DEFAULT_USE_DOCTOR_FRM 293
#define MOD_CONFIG_DEFAULT_USE_SCIENCE_FRM 293
#define MOD_CONFIG_DEFAULT_USE_REPAIR_FRM 293
#define MOD_CONFIG_DEFAULT_SCIENCE_REPAIR_TARGET_TYPE 0
#define MOD_CONFIG_DEFAULT_GAME_DIALOG_FIX 1
#define MOD_CONFIG_DEFAULT_GAME_DIALOG_GENDER_WORDS 0
#define MOD_CONFIG_DEFAULT_TWEAKS_FILE ""
#define MOD_CONFIG_DEFAULT_TOWN_MAP_HOTKEYS_FIX 1

// Mod metadata
#define MOD_INFO_MAX_NAME 128
#define MOD_INFO_MAX_DESC 512
#define MOD_INFO_MAX_AUTHOR 128
#define MOD_INFO_MAX_ICON 128
#define MOD_INFO_MAX_DEP_NAME 64
#define MOD_INFO_MAX_DEP 16
#define MAX_LOADED_MODS 64

typedef struct ModInfo {
    char name[MOD_INFO_MAX_NAME];
    char description[MOD_INFO_MAX_DESC];
    char author[MOD_INFO_MAX_AUTHOR];
    char dependencies[MOD_INFO_MAX_DEP][MOD_INFO_MAX_DEP_NAME];
    int dependencyCount;
    int icon_index;
    char filePath[COMPAT_MAX_PATH];
    char datName[MOD_INFO_MAX_NAME];
} ModInfo;

// Global list of loaded mods
extern ModInfo gLoadedMods[MAX_LOADED_MODS];
extern int gLoadedModsCount;

extern bool gModConfigInitialized;
extern Config gModConfig;

bool modConfigInit(int argc, char** argv);
void modConfigExit();

void modConfigWriteOrderFromLoadedMods();

} // namespace fallout

#endif /* MOD_CONFIG_H */
